name: Playwright UI Tests

on:
  workflow_dispatch:
    inputs:
      testPath:
        description: 'Directory or file path to run Playwright tests from'
        required: false
        default: 'tests/ui-cases'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Debug current working directory
        run: pwd && ls -R

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          echo "Running tests from path: ${{ github.event.inputs.testPath }}"
          npx playwright test "${{ github.event.inputs.testPath }}"
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}